# Generated by Django 4.0.3 on 2022-03-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='hidtoryid',
            new_name='historyid',
        ),
    ]
